### ISSUE TITLE
Irony with Visual Studio Code?

### ISSUE THREAD

**Issue by dhowe** [ironyproject/irony#1]
Is it possible? Or from a terminal/command-line? Other operating systems?

**Comment by yallie** [comment]
Hi,

>Irony with Visual Studio Code?

never tried that (yet).

This repository is currently just a clone of the closed codeplex project.
The nearest plans is to update the project to use the modern tooling.
.NET Standard targeting, VS code, etc.

>Or from a terminal? 

Sorry, don't understand the question :)

>Other operating systems?

I know that Irony was used with Mono, at least the parsing engine.
Not sure about the Grammar Explorer though, doesn't seem to be
possible (relies on WinForms and other non-portable dependencies).

Regards, Alex.

**Comment by mohchari** [comment]
I use Irony with Visual Studio Code on OSX. I forked the same archived Irony codeplex project and changed it to target .NET standard (among other changes). 

I was thinking of just starting my own repo with these changes, since I didn't really respect any backwards compatibility for Windows and removed all non-portable dependencies.

**Comment by yallie** [comment]
Looks like Visual Studio Code doesn't support VS solutions and projects natively.
It manipulates files and folders and relies on settings files like tasks.json and launch.json.
But once you've set these up, everything seems to work (building, editing, intellisense, etc):

![image](https://user-images.githubusercontent.com/672878/38178277-d0c27c7c-3617-11e8-849e-1dfb131c676f.png)

One big gotcha is that GrammarExplorer project isn't supported because it's WinForms.
And I can hardly imagine developing Irony grammars without the GrammarExplorer app.

But the parser/interpreter should now work on platforms supporting .NET Core 2.0.
